### ISSUE TITLE
not loading preview

### ISSUE THREAD

**Issue by Niutonian** [gokayfem/ComfyUI-Depth-Visualization#1]
Hello,
the preview node doesn't seem to work anymore with marigold node, 
There is no error message, it just passes the depth preview node without displaying anything

**Comment by gokayfem** [comment]
well, i have not changed a single line of code since i started this repository, i think it maybe caused by your browser cache. clean it and try again please. did you try it with other depth models? you can send the console log also. press F12 after you queue prompt.

**Comment by Niutonian** [comment]
@gokayfem I got it working by clearing my cache, thanks for the tip.

Quick extra question, do you have a way to output an image from your preview node, E.g: I change the angle to something I like, how can I save this image?

**Comment by gokayfem** [comment]
currently im working on advanced version of this node to visualize textures with ao_map, height_map, color_map, normal_map, roughness_map, metalness_map etc.. once i add the save option to that node. i will go back to this and add that to this node also.

**Comment by Niutonian** [comment]
Awesome, can't wait to give it a try.

One last thing I noticed, if the image is in portrait mode, the preview will always be a square, is there a way to maintain the original size.


![Screenshot 2024-03-22 074756](https://github.com/gokayfem/ComfyUI-Depth-Visualization/assets/89068652/1123e0d0-d0ec-4b50-9c85-4d679e23039b)

**Comment by gokayfem** [comment]
thanks for the great feedback, i will look into this too. i only tried it with square pictures sorry about that. i also need to add some options to play with depth map strength, light strength etc.

**Comment by Niutonian** [comment]
No stress, I'm really happy you built it, thanks for your quick support, 
Have a great day/evening +1

**Comment by gokayfem** [comment]
I've added save screenshot button

**Comment by gokayfem** [comment]
aspect ratio fixed
